[code]
co_argcount = 1
co_cellvars = []
co_code = [ 124, 0, 100, 1, 107, 6, 114, 12, 100, 2, 83, 0, 116, 0, 124, 0, 100, 2, 24, 0, 131, 1, 116, 0, 124, 0, 100, 3, 24, 0, 131, 1, 23, 0, 83, 0,]
co_consts = [ "None", [ 1, 2,], 1, 2,]
co_filename = "/home/shprexen/PycharmProjects/Serial/Tests/test_objects.py"
co_firstlineno = 25
co_flags = 67
co_freevars = []
co_kwonlyargcount = 0
co_lnotab = [ 0, 1, 8, 1, 4, 1,]
co_name = "fibonacci"
co_names = [ "fibonacci",]
co_nlocals = 1
co_posonlyargcount = 0
co_stacksize = 4
co_varnames = [ "n",]

[globals]
fibonacci = "fibonacci<function>"
__name__ = "test_objects"
__package__ = ""
__file__ = "/home/shprexen/PycharmProjects/Serial/Tests/test_objects.py"
__cached__ = "/home/shprexen/PycharmProjects/Serial/Tests/__pycache__/test_objects.cpython-38.pyc"
global_value = 5
